# -*- coding: utf-8 -*-
"""Introdução ao Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1omhw5SIbHM5HFjaAYWuIXuMKhpXLeW

# ANALISANDO NOTAS EM GERAL
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioId","filmeId","nota","momento"]
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota.plot(kind='hist')

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

filmes = pd.read_csv('movies.csv')
filmes.columns = ['filmeId','titulo','generos']
filmes.head()

notas.head()

"""# ANALISANDO NOTAS POR FILME"""

notas.query("filmeId==1").nota.mean()

media_por_filme = notas.groupby("filmeId").mean()["nota"]
print(media_por_filme)

media_por_filme.plot(kind='hist')

sns.boxplot(media_por_filme)

sns.distplot(media_por_filme, bins=10)

import matplotlib.pyplot as plt

plt.hist(media_por_filme)
plt.title("histograma das medias dos filmes")

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

tmdb.original_language.unique()

tmdb["original_language"].value_counts().index

contagem_de_lingua = tmdb["original_language"].value_counts().to_frame().reset_index()
contagem_de_lingua.columns = ["original_language","total"]
contagem_de_lingua.head()

sns.barplot(x="original_language",y="total", data = contagem_de_lingua)

sns.catplot(x="original_language",kind="count",data=tmdb)

total_por_lingua = tmdb["original_language"].value_counts()
total_geral = total_por_lingua.sum()
total_de_ingles = total_por_lingua.loc["en"]
total_do_resto = total_geral - total_de_ingles

dados = {
    'lingua':['ingles','outros'],
    'total':[total_de_ingles,total_do_resto] 
}
dados = pd.DataFrame(dados)
dados

sns.barplot(x="lingua",y="total",data=dados)

total_por_lingua_de_outros_filmes = tmdb.query("original_language != 'en'").original_language.value_counts()

filmes_sem_lingua_original_em_ingles = tmdb.query("original_language != 'en'")

sns.catplot(x="original_language",kind="count",data=filmes_sem_lingua_original_em_ingles,aspect=2,palette="GnBu_d",order=total_por_lingua_de_outros_filmes.index)

"""# MEDIA, MEDIANA, DP, ETC"""

notas.head()
notas_do_toy_story = notas.query("filmeId==1")
notas_do_jumanji = notas.query("filmeId==2")
print(len(notas_do_toy_story),len(notas_do_jumanji))

import numpy as np

sns.boxplot(x="filmeId",y="nota",data=notas.query("filmeId in [1,2]"))