# -*- coding: utf-8 -*-
"""Introdução ao Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1omhw5SIbHM5HFjaAYWuIXuMKhpXLeW

# ANALISANDO NOTAS EM GERAL
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioId","filmeId","nota","momento"]
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota.plot(kind='hist')

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

filmes = pd.read_csv('movies.csv')
filmes.columns = ['filmeId','titulo','generos']
filmes.head()

notas.head()

"""# ANALISANDO NOTAS POR FILME"""

notas.query("filmeId==1").nota.mean()

media_por_filme = notas.groupby("filmeId").mean()["nota"]
print(media_por_filme)

media_por_filme.plot(kind='hist')

sns.boxplot(media_por_filme)

sns.distplot(media_por_filme, bins=10)

import matplotlib.pyplot as plt

plt.hist(media_por_filme)
plt.title("histograma das medias dos filmes")

# tmdb['orignal_language'].value_counts()
# contagem_de_lingua = tmdb['orignal_language'].value_counts().to_frame().reset_index()
# 
# sns.barplot(x='original_language',y='total',data=contagem_de_lingua)
# sns.catplot(x='original_language',kind='count',data=tmdb)
# plt.pie(contagem_de_lingua["total"], labels = contagem_de_lingua["original_language"])
# total_por_lingua = tmdb["original_language"].value_counts()
# total_por_lingua.loc["en"]
# total_por_lingua = tmdb["original_language"].value_counts()
# total_geral = total_por_lingua.sum()
# total_de_ingles = total_por_lingua.loc["en"]
# total_do_resto = total_geral - total_de_ingles
# print(total_de_ingles, total_do_resto)
# tmdb.query("original_language == 'en'")
# tmdb.query("original_language != 'en'")
# tmdb.query("original_language != 'en'").original_language.value_counts()
# sns.catplot(x = "original_language", data = filmes_sem_lingua_original_em_ingles, kind="count")

# OUTRO TIPO DE GRÁFICO
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", height=4,
           scatter_kws={"s": 50, "alpha": 1})